version: "3"
services: 
    db:
        image: postgres
        container_name: "pg_container"
        environment:
            POSTGRES_PASSWORD: "root"
            POSTGRES_USER: "root"
            POSTGRES_DB: "test_db"
        ports: 
            - "5435:5432"
        volumes:
            - "./db:/var/lib/postgresql/data/"
